include_guard(GLOBAL)

include(${CMAKE_CURRENT_LIST_DIR}/impl/json.cmake)

function(burt_json_query json query out_var)
    set(_extra_vars ${ARGN})
    list(LENGTH _extra_vars _extra_var_count)
    set(err_msg "")
    if(${_extra_var_count} GREATER 0)
        list(GET _extra_vars 0 err_msg)
    endif()
    message(TRACE "Querying json with '${_query}'")
    if(json STREQUAL "")
        message(DEBUG "JSON string is empty")
    endif()
    if(query STREQUAL "")
        message(FATAL_ERROR "JSON query is missing")
    elseif(out_var STREQUAL "")
        message(FATAL_ERROR "JSON query result variable name is missing")
    endif()
    string(JSON _temp ERROR_VARIABLE _err GET ${json} ${query})
    if(NOT _err STREQUAL "NOTFOUND")
        set(_temp "NOTFOUND")
        message(DEBUG "JSON query failed: " ${_err})
        if(NOT err_msg STREQUAL "")
            message(FATAL_ERROR ${err_msg})
        endif()
    endif()
    set(${out_var} ${_temp} PARENT_SCOPE)
endfunction()
