include_guard(GLOBAL)

include(${CMAKE_CURRENT_LIST_DIR}/impl/json.cmake)

function(burt_json_query out_var json)
    set(_options)
    set(_single_args)
    set(_operations GET TYPE MEMBER LENGTH REMOVE SET EQUAL)
    set(_mult_args ${_operations} ERROR_MESSAGE)
    cmake_parse_arguments(_arg ${_options} ${_single_args} ${_multi_args} ${ARGN})

    # make sure there's a unique operand and get the query from it.
    set(_oper "")
    set(_query "")
    foreach(_oper ${_operations})
        if(NOT _oper STREQUAL "")
            message(FATAL_ERROR "burt_json_query cannot be called with more than one operand")
        endif()
        if(${_oper})
            set(_oper ${_oper})
            set(_query ${_arg_${_oper}})
        endif()
    endforeach()

    # Execute the JSON query and pass back the result or throw an error if there is one.
    string(JSON _temp ERROR_VARIABLE _err ${_oper} ${json} ${_query})
    if(NOT _err STREQUAL "NOTFOUND")
        set(_temp "NOTFOUND")
        message(DEBUG "JSON query failed: " ${_err})
        if(_arg_ERROR_MESSAGE)
            message(FATAL_ERROR ${_arg_ERROR_MESSAGE})
        endif()
    endif()
    set(${out_var} ${_temp} PARENT_SCOPE)
endfunction()
